# Generated by Django 4.1.5 on 2023-03-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=500)),
                ('tugilgan_yil', models.PositiveSmallIntegerField()),
                ('jins', models.CharField(max_length=200)),
                ('davlat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('narx', models.PositiveSmallIntegerField()),
                ('muddat', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('yil', models.DateField()),
                ('janr', models.CharField(max_length=500)),
                ('aktyorlar', models.ManyToManyField(to='film.aktyor')),
            ],
        ),
    ]
