# Generated by Django 4.1.5 on 2023-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktyor',
            name='tugilgan_yil',
            field=models.DateField(),
        ),
    ]
