# Generated by Django 4.1.5 on 2023-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_aktyor_tugilgan_yil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='narx',
            field=models.FloatField(),
        ),
    ]
