# Generated by Django 4.1.5 on 2023-03-17 12:03

import django.core.validators
from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_tarif_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktyor',
            name='davlat',
            field=models.CharField(max_length=200, validators=[film.models.validate_davlat]),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='narx',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
