# Generated by Django 4.1.7 on 2023-03-27 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import film.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0004_alter_aktyor_davlat_alter_tarif_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktyor',
            name='jins',
            field=models.CharField(max_length=200, validators=[film.models.validate_jins]),
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('kino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.kino')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
